# Generated by Django 5.2.8 on 2025-11-13 20:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("image_processing", "Image Processing"),
                            ("text_analysis", "Text Analysis"),
                            ("data_transformation", "Data Transformation"),
                            ("model_training", "Model Training"),
                            ("inference", "Inference"),
                            ("other", "Other"),
                        ],
                        help_text="Job type",
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        help_text="Current job status",
                        max_length=50,
                    ),
                ),
                (
                    "input_url",
                    models.URLField(
                        blank=True,
                        help_text="URL to input data/resource",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "progress",
                    models.IntegerField(
                        default=0, help_text="Job progress percentage (0-100)"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Job creation timestamp"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="User who created the job",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Job",
                "verbose_name_plural": "Jobs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="JobResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "result_url",
                    models.URLField(
                        blank=True,
                        help_text="URL to job result/output",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "meta",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional metadata in JSON format",
                    ),
                ),
                (
                    "finished_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Job completion timestamp"
                    ),
                ),
                (
                    "job",
                    models.OneToOneField(
                        help_text="Associated job",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="result",
                        to="core.job",
                    ),
                ),
            ],
            options={
                "verbose_name": "Job Result",
                "verbose_name_plural": "Job Results",
                "ordering": ["-finished_at"],
            },
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("admin", "Admin"),
                            ("editor", "Editor"),
                            ("viewer", "Viewer"),
                        ],
                        help_text="User role: Admin (full access), Editor (create/edit), Viewer (read-only)",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Profile creation timestamp"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Profile last update timestamp"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        help_text="Associated user",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Profile",
                "verbose_name_plural": "User Profiles",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(help_text="Project name", max_length=255)),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Project description", null=True
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Project creation timestamp"
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        help_text="Project owner",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owned_projects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Project",
                "verbose_name_plural": "Projects",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="job",
            name="project",
            field=models.ForeignKey(
                help_text="Parent project",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="jobs",
                to="core.project",
            ),
        ),
    ]
