# Generated by Django 5.2.8 on 2025-11-14 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_job_input_file_jobresult_logs_jobresult_result_file_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="meta",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Additional metadata in JSON format (job configuration, parameters, etc.)",
                null=True,
            ),
        ),
    ]
